// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using f1api.Data;

#nullable disable

namespace f1api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251209131834_SeedDriversData")]
    partial class SeedDriversData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("f1api.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RacingNumber")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Max Verstappen",
                            RacingNumber = 33,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "Sergio Perez",
                            RacingNumber = 11,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Name = "George Russell",
                            RacingNumber = 63,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Name = "Kimi Antonelli",
                            RacingNumber = 12,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            Name = "Charles Leclerc",
                            RacingNumber = 16,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            Name = "Lewis Hamilton",
                            RacingNumber = 44,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            Name = "Lando Norris",
                            RacingNumber = 4,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            Name = "Oscar Piastri",
                            RacingNumber = 81,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 9,
                            Description = "",
                            Name = "Fernando Alonso",
                            RacingNumber = 14,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            Name = "Lance Stroll",
                            RacingNumber = 18,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 11,
                            Description = "",
                            Name = "Pierre Gasly",
                            RacingNumber = 10,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 12,
                            Description = "",
                            Name = "Jack Doohan",
                            RacingNumber = 7,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 13,
                            Description = "",
                            Name = "Alexander Albon",
                            RacingNumber = 23,
                            TeamId = 7
                        },
                        new
                        {
                            Id = 14,
                            Description = "",
                            Name = "Carlos Sainz",
                            RacingNumber = 55,
                            TeamId = 7
                        },
                        new
                        {
                            Id = 15,
                            Description = "",
                            Name = "Yuki Tsunoda",
                            RacingNumber = 22,
                            TeamId = 8
                        },
                        new
                        {
                            Id = 16,
                            Description = "",
                            Name = "Liam Lawson",
                            RacingNumber = 30,
                            TeamId = 8
                        },
                        new
                        {
                            Id = 17,
                            Description = "",
                            Name = "Nico Hulkenberg",
                            RacingNumber = 27,
                            TeamId = 9
                        },
                        new
                        {
                            Id = 18,
                            Description = "",
                            Name = "GabrielBortoleto",
                            RacingNumber = 5,
                            TeamId = 9
                        },
                        new
                        {
                            Id = 19,
                            Description = "",
                            Name = "Esteban Ocon",
                            RacingNumber = 31,
                            TeamId = 10
                        },
                        new
                        {
                            Id = 20,
                            Description = "",
                            Name = "Oliver Bearman",
                            RacingNumber = 87,
                            TeamId = 10
                        });
                });

            modelBuilder.Entity("f1api.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Principal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("f1api.Models.Driver", b =>
                {
                    b.HasOne("f1api.Models.Team", "Team")
                        .WithMany("Drivers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("f1api.Models.Team", b =>
                {
                    b.Navigation("Drivers");
                });
#pragma warning restore 612, 618
        }
    }
}
